.\" SPDX-FileCopyrightText: 2026 Ingo Ruhnke <grumbel@gmail.com>
.\" SPDX-License-Identifier: GPL-3.0-or-later
.TH DT-RMDIR 1 "August 2026" "dirtoo tools" "User Commands"
.SH NAME
dt-rmdir \- remove empty directories
.SH SYNOPSIS
.B dt-rmdir
[\fIOPTIONS\fR]
.I DIR\fR...
.SH DESCRIPTION
Remove empty directories. Non-empty directories are reported as errors unless
options documented in
.B \-\-help
say otherwise.
.SH OPTIONS
.TP
.BR \-V ", " \-\-version
.TQ
.BR \-h ", " \-\-help
.SH SEE ALSO
.BR dirtoo (1),
.BR dt-copy (1),
.BR dt-move (1),
.BR dt-rename (1),
.BR dt-rm (1),
.BR dt-mkdir (1),
.BR dt-filter (1)
.SH AUTHOR
Written for the dirtoo project.
.SH COPYRIGHT
Copyright \(co 2026 Ingo Ruhnke. License GPL-3.0-or-later.
