.\" SPDX-FileCopyrightText: 2026 Ingo Ruhnke <grumbel@gmail.com>
.\" SPDX-License-Identifier: GPL-3.0-or-later
.TH DT-SYMLINK 1 "August 2026" "dirtoo tools" "User Commands"
.SH NAME
dt-symlink \- create symbolic links
.SH SYNOPSIS
.B dt-symlink
[\fIOPTIONS\fR]
.I TARGET
.I LINK\-PATH
.SH DESCRIPTION
Create a symbolic link at
.I LINK\-PATH
pointing to
.IR TARGET .
.SH OPTIONS
.TP
.BR \-n ", " \-\-dry\-run
.TQ
.BR \-v ", " \-\-verbose
.TQ
.BR \-V ", " \-\-version
.TQ
.BR \-h ", " \-\-help
.SH SEE ALSO
.BR dirtoo (1),
.BR dt-copy (1),
.BR dt-move (1),
.BR dt-rename (1),
.BR dt-rm (1),
.BR dt-mkdir (1),
.BR dt-filter (1)
.SH AUTHOR
Written for the dirtoo project.
.SH COPYRIGHT
Copyright \(co 2026 Ingo Ruhnke. License GPL-3.0-or-later.
